scsi: ufs: Mark `__ufshcd_cmd_log` as maybe unused
../drivers/scsi/ufs/ufshcd.c:791:13: error: unused function '__ufshcd_cmd_log' [-Werror,-Wunused-function]
static void __ufshcd_cmd_log(struct ufs_hba *hba, char *str, char *cmd_type,
            ^
1 error generated.

Change-Id: Ib37160f24925de16da18d22975c19d4e0f2886d6